apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: c3RvcmFnZWFjcw==
  azurestorageaccountkey: ajJBT1pwTGpCcjY2bmpqU3NlbG1CWmo5cWtGZ09NQ05JTVZ5N1ljN2s5MWZjQWEyeUQ1WEp5WUtRbmlKQzhsN0tFUTJEQUl4QVFwRUJTbGoySGsydVE9PQ==