FROM jenkins
#COPY plugins.txt /usr/share/jenkins/plugins.txt
#RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
USER root
#RUN apt-get update
#RUN apt-get install sudo
#RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
#RUN gpasswd -a jenkins root
#USER jenkins